---
  - hosts: 127.0.0.1
    tasks:
    - name: Cat JSON file to get it into Ansible
      shell: cat example.json
      register: json_file

    - name: Saving variable
      set_fact: json_var={{ (json_file.stdout | from_json)['info'][0]['id'] }}

    - debug: var=json_var
