---
  - hosts: 127.0.0.1
    tasks:
    - name: Cat JSON file to get it into Ansible
      shell: cat example.json
      register: json_file

    # - name: Saving variable
    #   set_fact: json_var={{ (json_file.stdout | from_json)[0]['id'] }}
    #
    # - debug: var=json_var

    - name: Display all Host Groups
      debug: var=item
      with_items: "{{json_file.stdout|from_json|json_query('[*].id')}}"
      when: json_file.stdout|from_json|json_query('[*].hostgroup') == "kafka-broker"

    - name: Display all Nodes
      debug: var=item
      with_items: "{{json_file.stdout|from_json|json_query('[*].node')|list}}"

# reference - https://stackoverflow.com/questions/36681994/create-a-list-of-dictionaries-from-host-groups-in-ansible-playbook
# reference - https://stackoverflow.com/questions/3
# reference - https://docs.ansible.com/ansible/latest/playbooks_filters.html#combining-hashes-dictionaries
    # - name: Creating JSON
    #   set_facts:
    #     output: "{{ outout|default([]) | combine({ 'hostgroup': item.hostgroup, })}}"
